version: '2.3'
services:
 application:
  build: 
    # context:\
    Dockerfile
  environment:
    - DISPLAY_ERRORS=On
    - MYSQL_HOST=mysql
    - MYSQL_USER="root"
    - MYSQL_PASSWORD=root
  # volumes:
  #     - ./data:/var/www/html
  ports:
    - 8000:80
  depends_on:
    - mysql
    
 mysql:
  image: mysql:5.7
  environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_USER}
  volumes:
    - ./data/migrations:/docker-entrypoint-inidb.depends_on
   
 adminer:
  image: adminer
  ports:
    - 8080:8080
  depends_on:
    - mysql        