version: '2.3'
services:
 app:
  image: aspnetapp 
  container_name: myapp_compose
  ports:
    - 10001:80
  depends_on:
    - db
 db:
  image: mydatabase
  container_name: mydb_compose
  ports:
    - 1441:1433  
  environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Pruebas2019..  